schema: '**/*.graphqls'
schemaEntrypoint: 'lib/type-defs.graphqls'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
documents: 
  - '**/*.graphql'
cacheDir: __generated__
config:   
